### ISSUE TITLE
Some binaries do not seem to work

### ISSUE THREAD

**Issue by jcelerier** [mariotaku/raspbian-sysroot-action#1]
I am trying this action to add an armhf sysroot to my build: 
- https://github.com/ossia/score/actions/runs/7528411330/job/20490563382
- https://github.com/ossia/score/blob/master/.github/workflows/embedded.yaml#L80

The build fails while trying to run a binary installed from debian, `moc` (comes with Qt): 

     /opt/pi-sysroot/usr/lib/qt6/libexec/moc: error while loading shared libraries: libpcre2-16.so.0: cannot open shared object file: No such file or directory

despite me installing libpcre2-16-0 in both the sysroot and the host for good measure. What are my options?

**Comment by mariotaku** [comment]
Hi, it looks like the toolchain tries to use Qt binaries provided by the target (should be the one on the host).
I'll try to find out how to solve that.

**Comment by jcelerier** [comment]
Thanks! :)

**Comment by mariotaku** [comment]
Hi, I didn't make a patch to the action itself to fix this issue, but did found a hack for your case: https://github.com/mariotaku/raspbian-sysroot-action/blob/9a43a1afe603f996debfc7d2b039969bcb1b231c/.github/workflows/build-tests.yml#L96-L102

**Comment by jcelerier** [comment]
great! I wonder if there isn't a cmake variable that could be used to direct Qt to the host tools when cross-compiling though, I'll investigate for maybe a simpler solution and report here if I find anything. thanks a lot!
